sudo: required

env: TEST_ENV=INTEGRATION

services:
  - docker

# command to install dependencies
install:
  - if [ "$TEST_ENV" = "UNITTEST" ]; then pip install -r requirements.txt; fi
  - if [ "$TEST_ENV" = "INTEGRATION" ]; then docker pull ilcdirac/slc6-base; fi

# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - ls $PYTHONPATH
  - if [ "$TEST_ENV" = "UNITTEST" ]; then py.test; fi
  - if [ "$TEST_ENV" = "INTEGRATION" ]; then docker run -i -t ilcdirac/slc6-base /bin/bash; fi
  - if [ "$TEST_ENV" = "INTEGRATION" ]; then ls; fi
