sudo: required

env: TEST_ENV=INTEGRATION

services:
  - docker
  - mysql

# command to install dependencies
install:
  - docker pull ilcdirac/slc6-base

# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - ls $PYTHONPATH
  - docker run -d -i -t -h localhost -v ${PWD}:/root/TestCode/DIRAC ilcdirac/slc6-base /bin/bash
  - export CONTAINER=`sudo docker ps -q`
  - docker exec $CONTAINER /bin/bash -c "cd && export VAR_Release=v6r14 && source TestCode/DIRAC/tests/Jenkins/dirac_ci.sh && fullInstallDIRAC"

