language: python

matrix:
  include:
    - python: 2.7
      env: TEST_ENV=UNITTEST
    - os: linux
      language: generic
      env: TEST_ENV=INTEGRATION
      sudo: required
  fast_finish: true

services:
  - docker

# command to install dependencies
install:
  - if [ "$TEST_ENV" = "UNITTEST" ]; then pip install -r requirements.txt; fi
  - if [ "$TEST_ENV" = "INTEGRATION" ]; then sudo docker pull ilcdirac/slc6-base; fi

# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - ls $PYTHONPATH
  - if [ "$TEST_ENV" = "UNITTEST" ]; then py.test; fi
