sudo: required

env: TEST_ENV=INTEGRATION

services:
  - docker

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysqladmin -u root password testDirac

# command to install dependencies
install:
  - docker pull ilcdirac/slc6-base

# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - ls $PYTHONPATH
  - docker run -d -i -t -p 3306:3306 -h localhost -v ${PWD}:/root/TestCode/DIRAC ilcdirac/slc6-base /bin/bash
  - export CONTAINER=`sudo docker ps -q`
  - docker exec $CONTAINER /bin/bash -c "cd && source TestCode/DIRAC/tests/Jenkins/setup_travis.sh && source TestCode/DIRAC/tests/Jenkins/dirac_ci.sh && fullInstallDIRAC"

