language: python
python:
  - "2.7"

git:
  depth: false

env:
  matrix:
    - CHECK=pytest
    - CHECK=docs
    - CHECK=pylint
    - CHECK=format
    - CHECK=tag

# command to install dependencies
install: 
  - "pip install --upgrade setuptools"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - ls $PYTHONPATH
  - if [[ "${CHECK}" == "pytest"  ]];
    then pytest;
    elif [[ "${CHECK}" == "docs"  ]];
    then cd docs; READTHEDOCS=True make html;
    elif [[ "${CHECK}" == "pylint"  ]];
    then travis_wait 30 .travis.d/runPylint.sh;
    elif [[ "${CHECK}" == "format" ]] && [[ "${TRAVIS_PULL_REQUEST}" != "false" ]];
    then git remote add GH https://github.com/DIRACGrid/DIRAC.git; git fetch --no-tags GH ${TRAVIS_BRANCH}; git branch -vv; git diff -U0 GH/${TRAVIS_BRANCH} | pycodestyle --diff;
    elif [[ "${CHECK}" == "tag" ]];
    then .travis.d/verify__init__.sh;
    fi

## ignore errors for sourcefiles "-i"
after_success:
  - if [[ "${CHECK}" == "pytest"  ]];
    then coveralls -i;
    fi
