sudo: required

language: generic

services:
  - docker

before_install:
- docker pull ilcdirac/slc6-base
- docker run ilcdirac/slc6-base /bin/bash -c "ls; cd; ls;"
- docker ps -a

script:
- ls
- cd
- ls
